name: "trucoshi-staging"

include:
  - path: docker-compose.networks.yml

services:
  postgres:
    networks:
      lightningaccountsnet:
        ipv4_address: 10.29.0.31
    extends:
      file: docker-compose.prod.yml
      service: postgres
  redis:
    networks:
      lightningaccountsnet:
        ipv4_address: 10.29.0.32
    extends:
      file: docker-compose.prod.yml
      service: redis
  server:
    networks:
      lightningaccountsnet:
        ipv4_address: 10.29.0.30
    extends:
      file: docker-compose.prod.yml
      service: server
