name: "trucoshi-${NODE_ENV:-test}"

include:
  - path: docker-compose.networks.yml

services:
  postgres_test_trucoshi:
    extends:
      file: docker-compose.base.yml
      service: postgres
  redis_test:
    extends:
      file: docker-compose.base.yml
      service: redis
  server:
    volumes:
      - ./src:/opt/app/src
    depends_on:
      postgres_test_trucoshi:
        condition: service_healthy
      redis_test:
        condition: service_started
    command: ["yarn", "test:e2e"]
    env_file:
      - path: ./.env.test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      APP_REDIS_URL: "redis://redis:6379"
      DATABASE_URL: "postgresql://${APP_DB_USER}:${APP_DB_PASSWORD}@postgres_test_trucoshi:5432/${APP_DB_NAME}?schema=public"
      APP_LIGHTNING_ACCOUNTS_URL: "http://host.docker.internal:3999/v1"
    extends:
      file: docker-compose.base.yml
      service: server
