services:
  server:
    volumes:
      - ../lightning-accounts/dist:/opt/app/node_modules/lightning-accounts/dist:ro
      - ../lightning-accounts/package.json:/opt/app/node_modules/lightning-accounts/package.json:ro
