services:
  postgres:
    restart: unless-stopped
    extends:
      file: docker-compose.base.yml
      service: postgres
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    restart: unless-stopped
    extends:
      file: docker-compose.base.yml
      service: redis
  trucoshi:
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    command: ["yarn", "start:prod:migrate"]
    extends:
      file: docker-compose.base.yml
      service: trucoshi

volumes:
  data:
  node_modules:
