services:
  postgres:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_DB_USER} -d ${APP_DB_NAME}"]
      interval: 5s
      start_period: 1s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    networks:
      lightningaccountsnet:
        ipv4_address: 10.29.0.31
  redis:
    image: redis:latest
    command: redis-server
    networks:
      lightningaccountsnet:
        ipv4_address: 10.29.0.32
  server:
    networks:
      lightningaccountsnet:
        ipv4_address: 10.29.0.30
    build:
      context: .
      args:
        PORT: ${APP_PORT}
    command: ["yarn", "start"]
    expose:
      - "${APP_PORT}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - path: ./.env

networks:
  default: null
  lightningaccountsnet:
    name: lightningaccountsnet
