# compose.yaml
version: "3.8"

services:
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  trucoshi:
    volumes:
      - "./src:/opt/app/src"
    extends:
      file: docker-compose.base.yml
      service: trucoshi

