# compose.yaml
version: "3.8"

services:
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
    volumes:
      - database-data:/var/lib/postgresql/data
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  trucoshi:
    command: ["yarn", "start:prod"]
    extends:
      file: docker-compose.base.yml
      service: trucoshi

volumes:
  database-data:
