name: "trucoshi-${NODE_ENV:-production}"

services:
  postgres:
    restart: always
    extends:
      file: docker-compose.base.yml
      service: postgres
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
  redis:
    restart: always
    extends:
      file: docker-compose.base.yml
      service: redis
  server:
    restart: always
    command: ["yarn", "start:prod:migrate"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    extends:
      file: docker-compose.base.yml
      service: server
