name: "trucoshi-${NODE_ENV:-production}"

include:
  - path: docker-compose.networks.yml

services:
  postgres:
    networks:
      lightningaccountsnet:
        ipv4_address: 10.30.0.21
    restart: always
    extends:
      file: docker-compose.base.yml
      service: postgres
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
  redis:
    networks:
      lightningaccountsnet:
        ipv4_address: 10.30.0.22
    restart: always
    extends:
      file: docker-compose.base.yml
      service: redis
  server:
    networks:
      lightningaccountsnet:
        ipv4_address: 10.30.0.20
    restart: always
    command: ["yarn", "start:prod"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_URL: "postgresql://${APP_DB_USER}:${APP_DB_PASSWORD}@postgres:5432/${APP_DB_NAME}?schema=public"
      APP_REDIS_URL: "redis://redis:6379"
    extends:
      file: docker-compose.base.yml
      service: server
