services:
  postgres:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_DB_USER} -d ${APP_DB_NAME}"]
      interval: 5s
      start_period: 1s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
  redis:
    image: redis:latest
    command: redis-server
  trucoshi:
    build:
      context: .
      args:
        PORT: ${APP_PORT}
    command: ["yarn", "start"]
    volumes:
      - node_modules:/opt/app/node_modules
    ports:
      - "${APP_PORT}:${APP_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - path: ./.env
    environment:
      DATABASE_URL: "postgresql://${APP_DB_USER}:${APP_DB_PASSWORD}@postgres:5432/${APP_DB_NAME}?schema=public"
      APP_REDIS_URL: "redis://redis:6379"
      APP_LIGHTNING_ACCOUNTS_URL: "http://host.docker.internal:2999/v1"
