services:
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  trucoshi:
    command: ["yarn", "test:e2e"]
    env_file:
      - path: ./.env.test
    environment:
      APP_LIGHTNING_ACCOUNTS_URL: "http://host.docker.internal:3999/v1"
    extends:
      file: docker-compose.base.yml
      service: trucoshi

volumes:
  node_modules: