name: "trucoshi-${NODE_ENV:-development}"

services:
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  server:
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    extends:
      file: docker-compose.base.yml
      service: server

volumes:
  node_modules:
