name: "trucoshi-${NODE_ENV:-production}"

services:
  postgres:
    restart: always
    extends:
      file: docker-compose.base.yml
      service: postgres
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
  redis:
    restart: always
    extends:
      file: docker-compose.base.yml
      service: redis
  server:
    restart: always
    command: ["yarn", "start:prod"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_URL: "postgresql://${APP_DB_USER}:${APP_DB_PASSWORD}@postgres:5432/${APP_DB_NAME}?schema=public"
      APP_REDIS_URL: "redis://redis:6379"
    extends:
      file: docker-compose.base.yml
      service: server
