services:
  postgres:
    restart: unless-stopped
    extends:
      file: docker-compose.base.yml
      service: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    restart: unless-stopped
    extends:
      file: docker-compose.base.yml
      service: redis
  trucoshi:
    restart: unless-stopped
    command: ["yarn", "start:prod:migrate"]
    extends:
      file: docker-compose.base.yml
      service: trucoshi

volumes:
  data:
  node_modules:
